project:
  type: website
  output-dir: docs
website:
  title: "Math For All"
  navbar:
    right:
      - about.qmd
      - text: "Numerical Analysis"
        href: posts/S1_NumericalAnalysis/index.qmd
      - text: "Statistics & Probability"
        href: posts/S2_Statistics/index.qmd
      - text: "Calculus"
        href: posts/S3_Calculus/index.qmd
      - text: "Life Matter"
        href: posts/S4_Rant/index.qmd
      - icon: github
        href: https://github.com/FaizAzhar
      - icon: linkedin
        href: https://www.linkedin.com/in/faiz-azhar241

  open-graph: true
  favicon: profile.jpg

format:
  html:
    theme: lux
    css: styles.css

editor: visual

