project:
  type: website
  output-dir: docs
website:
  title: "Math For All"
  navbar:
    right:
      - about.qmd
      - text: "Numerical Analysis"
        href: posts/S1_NumericalAnalysis/index.qmd
      - text: "Statistics & Probability"
        href: posts/S2_Statistics/index.qmd
      - text: "Calculus"
        href: posts/S3_Calculus/index.qmd
      - text: "Life Matter"
        href: posts/S4_Rant/index.qmd
      - icon: github
        href: https://github.com/FaizAzhar
      - icon: linkedin
        href: https://www.linkedin.com/in/faiz-azhar241

  open-graph: true
  favicon: profile.png

bibliography: biblio.bib
format:
  html:
    theme: lux
    css: styles.css

editor: visual

filters:
      - callouty-theorem
callouty-theorem:
  thm:
    override-title: false # do not override the title of the callout (title won't show when `appearance` set to `simple` or `minimal`)
    callout: # parameters of the wrapping callout. see Quarto documentation of callouts for more details
      type: note
      appearance: minimal
  prp:
    override-title: false
    callout:
      type: note
      appearance: minimal
  exr:
    override-title: false
    callout:
      type: tip
      appearance: minimal
  proof: # also support wrapping proof-like environments
    override-title: true # override the title of the callout by the name of the theorem
    callout:
      type: note
      appearance: default
      collapse: true
      icon: true
  solution:
    override-title: true
    callout:
      type: note
      appearance: default
      collapse: true
      icon: true
  remark:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: false
      icon: true
  cor: default # calloutify corollaries with default style
  def:
    override-title: true
    callout: default # also support default style here
